/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AccountLockedRouteImport } from './routes/account-locked'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmployeeQrTokenRouteImport } from './routes/verify-employee.$qrToken'
import { Route as AppWeeklyReportsRouteImport } from './routes/_app/weekly-reports'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppStandupRouteImport } from './routes/_app/standup'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMyLeavesRouteImport } from './routes/_app/my-leaves'
import { Route as AppMyAttendanceRouteImport } from './routes/_app/my-attendance'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppMeetingsRouteImport } from './routes/_app/meetings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCheckInRouteImport } from './routes/_app/check-in'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppAchievementsRouteImport } from './routes/_app/achievements'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminWeeklyReviewManagementRouteImport } from './routes/_app/admin/weekly-review-management'
import { Route as AppAdminWeeklyReportsRouteImport } from './routes/_app/admin/weekly-reports'
import { Route as AppAdminWeeklyFeedbackRouteImport } from './routes/_app/admin/weekly-feedback'
import { Route as AppAdminTasksRouteImport } from './routes/_app/admin/tasks'
import { Route as AppAdminStandupsRouteImport } from './routes/_app/admin/standups'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppAdminReportsRouteImport } from './routes/_app/admin/reports'
import { Route as AppAdminQrIdsRouteImport } from './routes/_app/admin/qr-ids'
import { Route as AppAdminProductivityRouteImport } from './routes/_app/admin/productivity'
import { Route as AppAdminNotificationsRouteImport } from './routes/_app/admin/notifications'
import { Route as AppAdminMeetingsRouteImport } from './routes/_app/admin/meetings'
import { Route as AppAdminLeavesRouteImport } from './routes/_app/admin/leaves'
import { Route as AppAdminEmployeesRouteImport } from './routes/_app/admin/employees'
import { Route as AppAdminEmployeeOfMonthRouteImport } from './routes/_app/admin/employee-of-month'
import { Route as AppAdminCardReaderAttendanceRouteImport } from './routes/_app/admin/card-reader-attendance'
import { Route as AppAdminAttendanceCorrectionsRouteImport } from './routes/_app/admin/attendance-corrections'
import { Route as AppAdminAttendanceRouteImport } from './routes/_app/admin/attendance'
import { Route as AppAdminApprovalsRouteImport } from './routes/_app/admin/approvals'
import { Route as AppAdminAchievementsRouteImport } from './routes/_app/admin/achievements'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLockedRoute = AccountLockedRouteImport.update({
  id: '/account-locked',
  path: '/account-locked',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmployeeQrTokenRoute = VerifyEmployeeQrTokenRouteImport.update({
  id: '/verify-employee/$qrToken',
  path: '/verify-employee/$qrToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWeeklyReportsRoute = AppWeeklyReportsRouteImport.update({
  id: '/weekly-reports',
  path: '/weekly-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppStandupRoute = AppStandupRouteImport.update({
  id: '/standup',
  path: '/standup',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMyLeavesRoute = AppMyLeavesRouteImport.update({
  id: '/my-leaves',
  path: '/my-leaves',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAttendanceRoute = AppMyAttendanceRouteImport.update({
  id: '/my-attendance',
  path: '/my-attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckInRoute = AppCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminWeeklyReviewManagementRoute =
  AppAdminWeeklyReviewManagementRouteImport.update({
    id: '/admin/weekly-review-management',
    path: '/admin/weekly-review-management',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminWeeklyReportsRoute = AppAdminWeeklyReportsRouteImport.update({
  id: '/admin/weekly-reports',
  path: '/admin/weekly-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminWeeklyFeedbackRoute = AppAdminWeeklyFeedbackRouteImport.update({
  id: '/admin/weekly-feedback',
  path: '/admin/weekly-feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTasksRoute = AppAdminTasksRouteImport.update({
  id: '/admin/tasks',
  path: '/admin/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStandupsRoute = AppAdminStandupsRouteImport.update({
  id: '/admin/standups',
  path: '/admin/standups',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminQrIdsRoute = AppAdminQrIdsRouteImport.update({
  id: '/admin/qr-ids',
  path: '/admin/qr-ids',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProductivityRoute = AppAdminProductivityRouteImport.update({
  id: '/admin/productivity',
  path: '/admin/productivity',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNotificationsRoute = AppAdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMeetingsRoute = AppAdminMeetingsRouteImport.update({
  id: '/admin/meetings',
  path: '/admin/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLeavesRoute = AppAdminLeavesRouteImport.update({
  id: '/admin/leaves',
  path: '/admin/leaves',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmployeesRoute = AppAdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmployeeOfMonthRoute = AppAdminEmployeeOfMonthRouteImport.update({
  id: '/admin/employee-of-month',
  path: '/admin/employee-of-month',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCardReaderAttendanceRoute =
  AppAdminCardReaderAttendanceRouteImport.update({
    id: '/admin/card-reader-attendance',
    path: '/admin/card-reader-attendance',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminAttendanceCorrectionsRoute =
  AppAdminAttendanceCorrectionsRouteImport.update({
    id: '/admin/attendance-corrections',
    path: '/admin/attendance-corrections',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminAttendanceRoute = AppAdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminApprovalsRoute = AppAdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAchievementsRoute = AppAdminAchievementsRouteImport.update({
  id: '/admin/achievements',
  path: '/admin/achievements',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-locked': typeof AccountLockedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/achievements': typeof AppAchievementsRoute
  '/calendar': typeof AppCalendarRoute
  '/check-in': typeof AppCheckInRoute
  '/dashboard': typeof AppDashboardRoute
  '/meetings': typeof AppMeetingsRoute
  '/messages': typeof AppMessagesRoute
  '/my-attendance': typeof AppMyAttendanceRoute
  '/my-leaves': typeof AppMyLeavesRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/standup': typeof AppStandupRoute
  '/tasks': typeof AppTasksRoute
  '/weekly-reports': typeof AppWeeklyReportsRoute
  '/verify-employee/$qrToken': typeof VerifyEmployeeQrTokenRoute
  '/admin/achievements': typeof AppAdminAchievementsRoute
  '/admin/approvals': typeof AppAdminApprovalsRoute
  '/admin/attendance': typeof AppAdminAttendanceRoute
  '/admin/attendance-corrections': typeof AppAdminAttendanceCorrectionsRoute
  '/admin/card-reader-attendance': typeof AppAdminCardReaderAttendanceRoute
  '/admin/employee-of-month': typeof AppAdminEmployeeOfMonthRoute
  '/admin/employees': typeof AppAdminEmployeesRoute
  '/admin/leaves': typeof AppAdminLeavesRoute
  '/admin/meetings': typeof AppAdminMeetingsRoute
  '/admin/notifications': typeof AppAdminNotificationsRoute
  '/admin/productivity': typeof AppAdminProductivityRoute
  '/admin/qr-ids': typeof AppAdminQrIdsRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/standups': typeof AppAdminStandupsRoute
  '/admin/tasks': typeof AppAdminTasksRoute
  '/admin/weekly-feedback': typeof AppAdminWeeklyFeedbackRoute
  '/admin/weekly-reports': typeof AppAdminWeeklyReportsRoute
  '/admin/weekly-review-management': typeof AppAdminWeeklyReviewManagementRoute
  '/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-locked': typeof AccountLockedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/achievements': typeof AppAchievementsRoute
  '/calendar': typeof AppCalendarRoute
  '/check-in': typeof AppCheckInRoute
  '/dashboard': typeof AppDashboardRoute
  '/meetings': typeof AppMeetingsRoute
  '/messages': typeof AppMessagesRoute
  '/my-attendance': typeof AppMyAttendanceRoute
  '/my-leaves': typeof AppMyLeavesRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/standup': typeof AppStandupRoute
  '/tasks': typeof AppTasksRoute
  '/weekly-reports': typeof AppWeeklyReportsRoute
  '/verify-employee/$qrToken': typeof VerifyEmployeeQrTokenRoute
  '/admin/achievements': typeof AppAdminAchievementsRoute
  '/admin/approvals': typeof AppAdminApprovalsRoute
  '/admin/attendance': typeof AppAdminAttendanceRoute
  '/admin/attendance-corrections': typeof AppAdminAttendanceCorrectionsRoute
  '/admin/card-reader-attendance': typeof AppAdminCardReaderAttendanceRoute
  '/admin/employee-of-month': typeof AppAdminEmployeeOfMonthRoute
  '/admin/employees': typeof AppAdminEmployeesRoute
  '/admin/leaves': typeof AppAdminLeavesRoute
  '/admin/meetings': typeof AppAdminMeetingsRoute
  '/admin/notifications': typeof AppAdminNotificationsRoute
  '/admin/productivity': typeof AppAdminProductivityRoute
  '/admin/qr-ids': typeof AppAdminQrIdsRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/standups': typeof AppAdminStandupsRoute
  '/admin/tasks': typeof AppAdminTasksRoute
  '/admin/weekly-feedback': typeof AppAdminWeeklyFeedbackRoute
  '/admin/weekly-reports': typeof AppAdminWeeklyReportsRoute
  '/admin/weekly-review-management': typeof AppAdminWeeklyReviewManagementRoute
  '/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/account-locked': typeof AccountLockedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/check-in': typeof AppCheckInRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/my-attendance': typeof AppMyAttendanceRoute
  '/_app/my-leaves': typeof AppMyLeavesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/standup': typeof AppStandupRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/weekly-reports': typeof AppWeeklyReportsRoute
  '/verify-employee/$qrToken': typeof VerifyEmployeeQrTokenRoute
  '/_app/admin/achievements': typeof AppAdminAchievementsRoute
  '/_app/admin/approvals': typeof AppAdminApprovalsRoute
  '/_app/admin/attendance': typeof AppAdminAttendanceRoute
  '/_app/admin/attendance-corrections': typeof AppAdminAttendanceCorrectionsRoute
  '/_app/admin/card-reader-attendance': typeof AppAdminCardReaderAttendanceRoute
  '/_app/admin/employee-of-month': typeof AppAdminEmployeeOfMonthRoute
  '/_app/admin/employees': typeof AppAdminEmployeesRoute
  '/_app/admin/leaves': typeof AppAdminLeavesRoute
  '/_app/admin/meetings': typeof AppAdminMeetingsRoute
  '/_app/admin/notifications': typeof AppAdminNotificationsRoute
  '/_app/admin/productivity': typeof AppAdminProductivityRoute
  '/_app/admin/qr-ids': typeof AppAdminQrIdsRoute
  '/_app/admin/reports': typeof AppAdminReportsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/standups': typeof AppAdminStandupsRoute
  '/_app/admin/tasks': typeof AppAdminTasksRoute
  '/_app/admin/weekly-feedback': typeof AppAdminWeeklyFeedbackRoute
  '/_app/admin/weekly-reports': typeof AppAdminWeeklyReportsRoute
  '/_app/admin/weekly-review-management': typeof AppAdminWeeklyReviewManagementRoute
  '/_app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-locked'
    | '/forgot-password'
    | '/login'
    | '/pending'
    | '/reset-password'
    | '/signup'
    | '/achievements'
    | '/calendar'
    | '/check-in'
    | '/dashboard'
    | '/meetings'
    | '/messages'
    | '/my-attendance'
    | '/my-leaves'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/standup'
    | '/tasks'
    | '/weekly-reports'
    | '/verify-employee/$qrToken'
    | '/admin/achievements'
    | '/admin/approvals'
    | '/admin/attendance'
    | '/admin/attendance-corrections'
    | '/admin/card-reader-attendance'
    | '/admin/employee-of-month'
    | '/admin/employees'
    | '/admin/leaves'
    | '/admin/meetings'
    | '/admin/notifications'
    | '/admin/productivity'
    | '/admin/qr-ids'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/standups'
    | '/admin/tasks'
    | '/admin/weekly-feedback'
    | '/admin/weekly-reports'
    | '/admin/weekly-review-management'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-locked'
    | '/forgot-password'
    | '/login'
    | '/pending'
    | '/reset-password'
    | '/signup'
    | '/achievements'
    | '/calendar'
    | '/check-in'
    | '/dashboard'
    | '/meetings'
    | '/messages'
    | '/my-attendance'
    | '/my-leaves'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/standup'
    | '/tasks'
    | '/weekly-reports'
    | '/verify-employee/$qrToken'
    | '/admin/achievements'
    | '/admin/approvals'
    | '/admin/attendance'
    | '/admin/attendance-corrections'
    | '/admin/card-reader-attendance'
    | '/admin/employee-of-month'
    | '/admin/employees'
    | '/admin/leaves'
    | '/admin/meetings'
    | '/admin/notifications'
    | '/admin/productivity'
    | '/admin/qr-ids'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/standups'
    | '/admin/tasks'
    | '/admin/weekly-feedback'
    | '/admin/weekly-reports'
    | '/admin/weekly-review-management'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/account-locked'
    | '/forgot-password'
    | '/login'
    | '/pending'
    | '/reset-password'
    | '/signup'
    | '/_app/achievements'
    | '/_app/calendar'
    | '/_app/check-in'
    | '/_app/dashboard'
    | '/_app/meetings'
    | '/_app/messages'
    | '/_app/my-attendance'
    | '/_app/my-leaves'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/standup'
    | '/_app/tasks'
    | '/_app/weekly-reports'
    | '/verify-employee/$qrToken'
    | '/_app/admin/achievements'
    | '/_app/admin/approvals'
    | '/_app/admin/attendance'
    | '/_app/admin/attendance-corrections'
    | '/_app/admin/card-reader-attendance'
    | '/_app/admin/employee-of-month'
    | '/_app/admin/employees'
    | '/_app/admin/leaves'
    | '/_app/admin/meetings'
    | '/_app/admin/notifications'
    | '/_app/admin/productivity'
    | '/_app/admin/qr-ids'
    | '/_app/admin/reports'
    | '/_app/admin/settings'
    | '/_app/admin/standups'
    | '/_app/admin/tasks'
    | '/_app/admin/weekly-feedback'
    | '/_app/admin/weekly-reports'
    | '/_app/admin/weekly-review-management'
    | '/_app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AccountLockedRoute: typeof AccountLockedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmployeeQrTokenRoute: typeof VerifyEmployeeQrTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-locked': {
      id: '/account-locked'
      path: '/account-locked'
      fullPath: '/account-locked'
      preLoaderRoute: typeof AccountLockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-employee/$qrToken': {
      id: '/verify-employee/$qrToken'
      path: '/verify-employee/$qrToken'
      fullPath: '/verify-employee/$qrToken'
      preLoaderRoute: typeof VerifyEmployeeQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/weekly-reports': {
      id: '/_app/weekly-reports'
      path: '/weekly-reports'
      fullPath: '/weekly-reports'
      preLoaderRoute: typeof AppWeeklyReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/standup': {
      id: '/_app/standup'
      path: '/standup'
      fullPath: '/standup'
      preLoaderRoute: typeof AppStandupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-leaves': {
      id: '/_app/my-leaves'
      path: '/my-leaves'
      fullPath: '/my-leaves'
      preLoaderRoute: typeof AppMyLeavesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-attendance': {
      id: '/_app/my-attendance'
      path: '/my-attendance'
      fullPath: '/my-attendance'
      preLoaderRoute: typeof AppMyAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/check-in': {
      id: '/_app/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AppCheckInRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/weekly-review-management': {
      id: '/_app/admin/weekly-review-management'
      path: '/admin/weekly-review-management'
      fullPath: '/admin/weekly-review-management'
      preLoaderRoute: typeof AppAdminWeeklyReviewManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/weekly-reports': {
      id: '/_app/admin/weekly-reports'
      path: '/admin/weekly-reports'
      fullPath: '/admin/weekly-reports'
      preLoaderRoute: typeof AppAdminWeeklyReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/weekly-feedback': {
      id: '/_app/admin/weekly-feedback'
      path: '/admin/weekly-feedback'
      fullPath: '/admin/weekly-feedback'
      preLoaderRoute: typeof AppAdminWeeklyFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tasks': {
      id: '/_app/admin/tasks'
      path: '/admin/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AppAdminTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/standups': {
      id: '/_app/admin/standups'
      path: '/admin/standups'
      fullPath: '/admin/standups'
      preLoaderRoute: typeof AppAdminStandupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/reports': {
      id: '/_app/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/qr-ids': {
      id: '/_app/admin/qr-ids'
      path: '/admin/qr-ids'
      fullPath: '/admin/qr-ids'
      preLoaderRoute: typeof AppAdminQrIdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/productivity': {
      id: '/_app/admin/productivity'
      path: '/admin/productivity'
      fullPath: '/admin/productivity'
      preLoaderRoute: typeof AppAdminProductivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/notifications': {
      id: '/_app/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AppAdminNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/meetings': {
      id: '/_app/admin/meetings'
      path: '/admin/meetings'
      fullPath: '/admin/meetings'
      preLoaderRoute: typeof AppAdminMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/leaves': {
      id: '/_app/admin/leaves'
      path: '/admin/leaves'
      fullPath: '/admin/leaves'
      preLoaderRoute: typeof AppAdminLeavesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/employees': {
      id: '/_app/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AppAdminEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/employee-of-month': {
      id: '/_app/admin/employee-of-month'
      path: '/admin/employee-of-month'
      fullPath: '/admin/employee-of-month'
      preLoaderRoute: typeof AppAdminEmployeeOfMonthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/card-reader-attendance': {
      id: '/_app/admin/card-reader-attendance'
      path: '/admin/card-reader-attendance'
      fullPath: '/admin/card-reader-attendance'
      preLoaderRoute: typeof AppAdminCardReaderAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/attendance-corrections': {
      id: '/_app/admin/attendance-corrections'
      path: '/admin/attendance-corrections'
      fullPath: '/admin/attendance-corrections'
      preLoaderRoute: typeof AppAdminAttendanceCorrectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/attendance': {
      id: '/_app/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AppAdminAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/approvals': {
      id: '/_app/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AppAdminApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/achievements': {
      id: '/_app/admin/achievements'
      path: '/admin/achievements'
      fullPath: '/admin/achievements'
      preLoaderRoute: typeof AppAdminAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCheckInRoute: typeof AppCheckInRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppMyAttendanceRoute: typeof AppMyAttendanceRoute
  AppMyLeavesRoute: typeof AppMyLeavesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStandupRoute: typeof AppStandupRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWeeklyReportsRoute: typeof AppWeeklyReportsRoute
  AppAdminAchievementsRoute: typeof AppAdminAchievementsRoute
  AppAdminApprovalsRoute: typeof AppAdminApprovalsRoute
  AppAdminAttendanceRoute: typeof AppAdminAttendanceRoute
  AppAdminAttendanceCorrectionsRoute: typeof AppAdminAttendanceCorrectionsRoute
  AppAdminCardReaderAttendanceRoute: typeof AppAdminCardReaderAttendanceRoute
  AppAdminEmployeeOfMonthRoute: typeof AppAdminEmployeeOfMonthRoute
  AppAdminEmployeesRoute: typeof AppAdminEmployeesRoute
  AppAdminLeavesRoute: typeof AppAdminLeavesRoute
  AppAdminMeetingsRoute: typeof AppAdminMeetingsRoute
  AppAdminNotificationsRoute: typeof AppAdminNotificationsRoute
  AppAdminProductivityRoute: typeof AppAdminProductivityRoute
  AppAdminQrIdsRoute: typeof AppAdminQrIdsRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminStandupsRoute: typeof AppAdminStandupsRoute
  AppAdminTasksRoute: typeof AppAdminTasksRoute
  AppAdminWeeklyFeedbackRoute: typeof AppAdminWeeklyFeedbackRoute
  AppAdminWeeklyReportsRoute: typeof AppAdminWeeklyReportsRoute
  AppAdminWeeklyReviewManagementRoute: typeof AppAdminWeeklyReviewManagementRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCheckInRoute: AppCheckInRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppMyAttendanceRoute: AppMyAttendanceRoute,
  AppMyLeavesRoute: AppMyLeavesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStandupRoute: AppStandupRoute,
  AppTasksRoute: AppTasksRoute,
  AppWeeklyReportsRoute: AppWeeklyReportsRoute,
  AppAdminAchievementsRoute: AppAdminAchievementsRoute,
  AppAdminApprovalsRoute: AppAdminApprovalsRoute,
  AppAdminAttendanceRoute: AppAdminAttendanceRoute,
  AppAdminAttendanceCorrectionsRoute: AppAdminAttendanceCorrectionsRoute,
  AppAdminCardReaderAttendanceRoute: AppAdminCardReaderAttendanceRoute,
  AppAdminEmployeeOfMonthRoute: AppAdminEmployeeOfMonthRoute,
  AppAdminEmployeesRoute: AppAdminEmployeesRoute,
  AppAdminLeavesRoute: AppAdminLeavesRoute,
  AppAdminMeetingsRoute: AppAdminMeetingsRoute,
  AppAdminNotificationsRoute: AppAdminNotificationsRoute,
  AppAdminProductivityRoute: AppAdminProductivityRoute,
  AppAdminQrIdsRoute: AppAdminQrIdsRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminStandupsRoute: AppAdminStandupsRoute,
  AppAdminTasksRoute: AppAdminTasksRoute,
  AppAdminWeeklyFeedbackRoute: AppAdminWeeklyFeedbackRoute,
  AppAdminWeeklyReportsRoute: AppAdminWeeklyReportsRoute,
  AppAdminWeeklyReviewManagementRoute: AppAdminWeeklyReviewManagementRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AccountLockedRoute: AccountLockedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmployeeQrTokenRoute: VerifyEmployeeQrTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
